#!/bin/sh
export DOTPATH=~/.dotfiles
GITHUB_URL="https://github.com/miso24/dotfiles"
ARCHIVE_GITHUB_URL="https://github.com/miso24/dotflies/archive/master.tar.gz"

dotfiles=()
deny_list=(".git" ".gitignore" ".gitmodules" ".DS_Store")

function is_exists() {
  which "$1" > /dev/null 2>&1
  return $?
}

function get_dotfiles() {
  dotfiles=("bin" "etc")

  # dotfiles
  for file in .??* ; do
    is_allow=true
    # filter
    for d_file in ${deny_list[@]}; do
      if [[ "$d_file" == "$file" ]]; then
        is_allow=false
      fi
    done
    # add dotfiles
    if ${is_allow} ; then
      dotfiles+=($file)
    fi
  done
}

function dotfiles_deploy() {
  cd $DOTPATH
  if [ $? -ne 0 ]; then
    echo "Failed to move $DOTPATH"
    return -1
  fi

  if [ ${#dotfiles[@]} -eq 0 ]; then
    get_dotfiles
  fi

  # symlink
  for file in ${dotfiles[@]} ; do
    ln -snfv "$DOTPATH/$file" "$HOME/$file"
  done
}

function dotfiles_initialize() {
  echo "Not implemented now!"
  return -1
}

function dotfiles_download() {
  if [ -d "$DOTPATH" ]; then
    echo "$DOTPATH is already exists"
    return -1
  fi

  if is_exists "git"; then
    # donwload by git
    git clone --recursive "$GITHUB_URL" "$DOTPATH"
  elif is_exists "curl"; then
    # donwload by curl
    curl "$ARCHIVE_GITHUB_URL" | tar xvz
    mv -f dotfiles-master $DOTPATH
  else
    echo "Oops! Please install curl or git"
    return -1
  fi
}

function dotfiles_install() {
  dotfiles_download

  dotfiles_deploy
}

dotfiles_install
